server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjhjminh0598/e-commerce-config
          default-label: main
          clone-on-start: true