server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjhjminh0598/e-commerce-config
          default-label: main
          clone-on-start: true
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
