spring:
  application:
    name: user-service
  config:
    import: "configserver:"  # ✅ REQUIRED for Spring Boot 3.x
  cloud:
    config:
      uri: http://localhost:8888  # Fetch configs from Cloud Config Server
      fail-fast: true  # Fail startup if Cloud Config Server is unavailable
    bus:
      enabled: true
