server:
  port: 3025

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3310/order_db
    username: admin
    password: giangnt@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  cloud:
    loadbalancer:
      instances:
        product-service:
          - http://localhost:2025
          - http://localhost:2026


user:
  service:
    url: http://user-service

product:
  service:
    url: http://product-service
